### ISSUE TITLE
Login unexpected exception 

### ISSUE THREAD

**Issue by JXGA** [cdnninja/yoto_ha#17]
Firstly, great project. Incredible progress in such a short time. 

I finally got around to adding V1.3.0 today. Upon login, received this error:

```
Logger: custom_components.yoto.config_flow
Source: custom_components/yoto/config_flow.py:104
integration: Yoto ([documentation](https://github.com/cdnninja/yoto_ha), [issues](https://github.com/cdnninja/yoto_ha/issues))
First occurred: 14:22:03 (2 occurrences)
Last logged: 14:22:42

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/yoto/config_flow.py", line 104, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/yoto/config_flow.py", line 45, in validate_input
    await hass.async_add_executor_job(ym.check_and_refresh_token)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 49, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 26, in initialize
    self.update_players_status()
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 32, in update_players_status
    self.api.update_players(self.token, self.players)
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoAPI.py", line 138, in update_players
    players[deviceId].plugged_in = POWER_SOURCE[
                                   ^^^^^^^^^^^^^
KeyError: 0
``` 

Thank you

**Comment by cdnninja** [comment]
1.3.1 should solve this.  Should be available in a few minutes.

**Comment by cjb0001** [comment]
Before closing then issue, per my testing please add the value of 5 for USB Power.

**Comment by JXGA** [comment]
Great, thank you very much!
