### ISSUE TITLE
Unexpected exception when trying to Authenticate

### ISSUE THREAD

**Issue by MrSlaggy** [cdnninja/yoto_ha#41]
When Trying to authenticate with the integration (Instaleld via HACs I get the follwoing:

![image](https://github.com/cdnninja/yoto_ha/assets/67077025/baa2ff1f-16fa-433e-8596-c348d0e5f8ac)

Error from logs:

`This error originated from a custom integration.

Logger: custom_components.yoto.config_flow
Source: custom_components/yoto/config_flow.py:104
integration: Yoto (documentation, issues)
First occurred: 11:27:19 AM (2 occurrences)
Last logged: 11:29:11 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/yoto/config_flow.py", line 104, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/yoto/config_flow.py", line 45, in validate_input
    await hass.async_add_executor_job(ym.check_and_refresh_token)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 57, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 27, in initialize
    self.update_players_status()
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 33, in update_players_status
    self.api.update_players(self.token, self.players)
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoAPI.py", line 131, in update_players
    players[deviceId].night_light_mode = LIGHT_COLORS[
                                         ^^^^^^^^^^^^^
KeyError: '0x641600'`

Core: 2024.5.3
Supervisor: 2024.05.1
Operating System: 12.3
Frontend@ 20240501.1

**Comment by cdnninja** [comment]
Do you know what color was set for the light at the time this occurred?

**Comment by cdnninja** [comment]
New version covers this color but not sure what it is so set as blank.

**Comment by MrSlaggy** [comment]
I have two. The lights were set to:
Yoto1: Orange
Yoto2: Yellow

**Comment by cdnninja** [comment]
Okay we can dial that in with time.    Please update and see if you can install now.

**Comment by MrSlaggy** [comment]
Spectacular. All Logged in. Thank you so much
