### ISSUE TITLE
Feature Priorities

### ISSUE THREAD

**Issue by cdnninja** [cdnninja/yoto_ha#56]
I'm interested to hear what others want added next?  Lots I could do but only so much time.

**Comment by WhimsySpoon** [comment]
You're obviously at the mercy of what's available from Yoto's API, but I'd love to see real-time updates, or as close to real-time as possible.

Plus the option to play/pause/turn on and off the player via the media player card or via the existing media player service calls. I tried this last night on 1.10.4 and nothing was happening.

Also, is it possible to return the name of the card being played? I can see the track name returned, but I'm wondering if we had the card name, would it be possible to grab the card artwork for the media player card? Looking at the [shop front](https://uk.yotoplay.com/collections/library), the image URLs aren't that [nicely formed](https://cdn.shopify.com/s/files/1/0051/8845/2401/files/Y3133YOTO02605JulietaandtheDiamondEnigma_Digital_WR_US__Rounded_200x.png?v=1714559951), so that may not be possible.

**Comment by bigmahlman** [comment]
Just wanted to say this is awesome! Keep up the good work.

**Comment by cjb0001** [comment]
I had the same issue with a mini. Here is the error in the log.
```
2024-05-24 10:07:16.441 ERROR (MainThread) [custom_components.yoto.coordinator] Unexpected error fetching yoto data
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/yoto/coordinator.py", line 62, in _async_update_data
await self.hass.async_add_executor_job(self.yoto_manager.update_players_status)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 35, in update_players_status
mqtt.update_status()
TypeError: YotoMQTTClient.update_status() missing 1 required positional argument: 'deviceId'
```

**Comment by cdnninja** [comment]
> I had the same issue with a mini. Here is the error in the log.
> 
> ```
> 2024-05-24 10:07:16.441 ERROR (MainThread) [custom_components.yoto.coordinator] Unexpected error fetching yoto data
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
> self.data = await self._async_update_data()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/config/custom_components/yoto/coordinator.py", line 62, in _async_update_data
> await self.hass.async_add_executor_job(self.yoto_manager.update_players_status)
> File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
> result = self.fn(*self.args, **self.kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 35, in update_players_status
> mqtt.update_status()
> TypeError: YotoMQTTClient.update_status() missing 1 required positional argument: 'deviceId'
> ```

https://github.com/cdnninja/yoto_api/commit/f4d5e25c25e1d81a0e963aba619853d945f71f96 should solve that.

**Comment by cdnninja** [comment]
Artwork has been added now.

**Comment by cjb0001** [comment]
Can I make a perhaps controversial proposal? Instead of using the card artwork for the player, use the 16x16 icon (track or chapter? I think they're always the same?). To me, it's more inline with the idea behind Yoto.  I would then ask that the card artwork is added as an extra_state_attribute. If we really wanted to over-complicate things, giving the user a choice of selecting between the icon and the card artwork in the integration configuration would be interesting.

As long was we're adding attributes, might as well be comprehensive..

Name | Yoto
-- | --
media_album_artist | card.metadata.author
media_album_name | card.title
media_image_url | tracks.display.icon16x16  [or chapter]
extra_state_attributes   // media_album_image_url | card.metadata.cover.imageL


I can work on a PR for some of these, now that I see how you've pulled in card info.

**Comment by cdnninja** [comment]
I'm open to giving it a try! My only worry is the low resolution aspect for the dashboards may not look good.  Not sure if we can use both images? Since dashboard needs high resolution but some views icon is perfect! 

Not sure all the data is mapped in the api library yet but not hard to do.

**Comment by WhimsySpoon** [comment]
I love the idea of the Yoto-style artwork!

I'm on 1.10.9 and I don't have any artwork appearing at all (everything else is working as it's keeping updated with the device). I've tried using the native HA media player card as well as custom mini-media-player card without luck.

I can't see anything artwork-related in the logs.

**Comment by WhimsySpoon** [comment]
> [cdnninja/yoto_api@f4d5e25](https://github.com/cdnninja/yoto_api/commit/f4d5e25c25e1d81a0e963aba619853d945f71f96) should solve that. 1.10.9 includes this.

I'm using 1.10.9 and I still find that I have to reload the integration after power-cycling the player to get it to update. The logs are completely silent until I reload the integration. Once reloaded, everything works perfectly.

I'm going to leave it for a while  to see if if happens again then review the logs to see if there was an error.

**Comment by WhimsySpoon** [comment]
> I'm going to leave it for a while to see if if happens again then review the logs to see if there was an error.

Didn't take long. I just paused the v2 player using the button on the device and HA didn't update, and is no longer updating.

The last messages in the log:

````
2024-05-25 14:37:34.497 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Topic: device/y2f4BaktzJvyNwSwRAcPRX6j/events
2024-05-25 14:37:34.497 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Message: {"trackLength":368,"position":79,"cardId":"eBpqG","repeatAll":true,"source":"card","cardUpdatedAt":"2021-01-06T10:49:51.084Z","chapterTitle":"The Highway Rat Game","chapterKey":"03","trackTitle":"The Highway Rat Game","trackKey":"03","streaming":false,"volume":4,"volumeMax":16,"playbackStatus":"playing","playbackWait":false,"sleepTimerActive":false,"eventUtc":1716644253}
2024-05-25 14:37:34.497 DEBUG (Thread-682 (_thread_main)) [custom_components.yoto.coordinator] Manually updated yoto data
2024-05-25 14:37:39.546 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Topic: device/y2f4BaktzJvyNwSwRAcPRX6j/events
2024-05-25 14:37:39.546 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Message: {"trackLength":368,"position":84,"cardId":"eBpqG","repeatAll":true,"source":"card","cardUpdatedAt":"2021-01-06T10:49:51.084Z","chapterTitle":"The Highway Rat Game","chapterKey":"03","trackTitle":"The Highway Rat Game","trackKey":"03","streaming":false,"volume":4,"volumeMax":16,"playbackStatus":"playing","playbackWait":false,"sleepTimerActive":false,"eventUtc":1716644258}
2024-05-25 14:37:39.546 DEBUG (Thread-682 (_thread_main)) [custom_components.yoto.coordinator] Manually updated yoto data
2024-05-25 14:37:44.644 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Topic: device/y2f4BaktzJvyNwSwRAcPRX6j/events
2024-05-25 14:37:44.644 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Message: {"trackLength":368,"position":88,"cardId":"eBpqG","repeatAll":true,"source":"card","cardUpdatedAt":"2021-01-06T10:49:51.084Z","chapterTitle":"The Highway Rat Game","chapterKey":"03","trackTitle":"The Highway Rat Game","trackKey":"03","streaming":false,"volume":4,"volumeMax":16,"playbackStatus":"playing","playbackWait":false,"sleepTimerActive":false,"eventUtc":1716644263}
2024-05-25 14:37:44.644 DEBUG (Thread-682 (_thread_main)) [custom_components.yoto.coordinator] Manually updated yoto data
2024-05-25 14:37:49.694 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Topic: device/y2f4BaktzJvyNwSwRAcPRX6j/events
2024-05-25 14:37:49.694 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Message: {"trackLength":368,"position":96,"cardId":"eBpqG","repeatAll":true,"source":"card","cardUpdatedAt":"2021-01-06T10:49:51.084Z","chapterTitle":"The Highway Rat Game","chapterKey":"03","trackTitle":"The Highway Rat Game","trackKey":"03","streaming":false,"volume":4,"volumeMax":16,"playbackStatus":"playing","playbackWait":false,"sleepTimerActive":false,"eventUtc":1716644268}
2024-05-25 14:37:49.694 DEBUG (Thread-682 (_thread_main)) [custom_components.yoto.coordinator] Manually updated yoto data
2024-05-25 14:37:54.766 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Topic: device/y2f4BaktzJvyNwSwRAcPRX6j/events
2024-05-25 14:37:54.766 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Message: {"trackLength":368,"position":100,"cardId":"eBpqG","repeatAll":true,"source":"card","cardUpdatedAt":"2021-01-06T10:49:51.084Z","chapterTitle":"The Highway Rat Game","chapterKey":"03","trackTitle":"The Highway Rat Game","trackKey":"03","streaming":false,"volume":4,"volumeMax":16,"playbackStatus":"playing","playbackWait":false,"sleepTimerActive":false,"eventUtc":1716644274}
2024-05-25 14:37:54.766 DEBUG (Thread-682 (_thread_main)) [custom_components.yoto.coordinator] Manually updated yoto data
2024-05-25 14:37:59.831 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Topic: device/y2f4BaktzJvyNwSwRAcPRX6j/events
2024-05-25 14:37:59.831 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Message: {"trackLength":368,"position":105,"cardId":"eBpqG","repeatAll":true,"source":"card","cardUpdatedAt":"2021-01-06T10:49:51.084Z","chapterTitle":"The Highway Rat Game","chapterKey":"03","trackTitle":"The Highway Rat Game","trackKey":"03","streaming":false,"volume":4,"volumeMax":16,"playbackStatus":"playing","playbackWait":false,"sleepTimerActive":false,"eventUtc":1716644279}
2024-05-25 14:37:59.831 DEBUG (Thread-682 (_thread_main)) [custom_components.yoto.coordinator] Manually updated yoto data
2024-05-25 14:40:46.200 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Topic: device/y2f4BaktzJvyNwSwRAcPRX6j/status
2024-05-25 14:40:46.200 DEBUG (Thread-682 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - MQTT Message: {"status":{"battery":3486,"powerCaps":"","batteryLevel":10,"batteryTemp":0,"batteryData":"0:0:0","batteryLevelRaw":10,"free":3724036,"freeDMA":97130,"free32":105678,"upTime":613,"utcTime":1716644445,"aliveTime":4932380,"errorsLogged":24,"nightlightMode":"off"}}
````

**Comment by cdnninja** [comment]
When you open and browse the app does it recover and update data? 

The media art is in master but not a version. To get that go to developer services.  Find the install service. Select the yoto entity and type "master" as the version.  Lowercase m.

**Comment by cdnninja** [comment]
As a note I would expect if the player doesn't send another update after that last message the home assistant plugin should poll for update every 30 minutes.  Offline players for example stop pushing updates.

**Comment by WhimsySpoon** [comment]
Ok, tried again.

Updated to `master`, started playing a card. Nothing in the logs, status was "off" for the media player entity. The app was correct and following changes.

Re-loading the integration fired a flurry of logs, terminating with:

````
2024-05-25 16:02:42.942 DEBUG (MainThread) [custom_components.yoto.coordinator] Finished fetching yoto data in 1.403 seconds (success: True)
2024-05-25 16:02:42.958 DEBUG (Thread-108 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - b'DASHy2f4BaktzJvyNwSwRAcPRX6j' - MQTT Disconnected: 7
2024-05-25 16:02:42.986 DEBUG (Thread-109 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - b'DASHy2fFAhHfRrI6vi7VXbUOQTeD' - MQTT connected: 0
2024-05-25 16:02:44.028 DEBUG (Thread-108 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - b'DASHy2f4BaktzJvyNwSwRAcPRX6j' - MQTT connected: 0
````

But the integration is still not tracking the device and the logs have stopped.

I tried to turn off the player, re-load the integration, turn on the player. Lots of logs, ending with:

````
2024-05-25 16:05:35.144 DEBUG (MainThread) [custom_components.yoto.coordinator] Finished fetching yoto data in 1.666 seconds (success: True)
2024-05-25 16:05:35.158 DEBUG (Thread-110 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - b'DASHy2f4BaktzJvyNwSwRAcPRX6j' - MQTT Disconnected: 7
2024-05-25 16:05:35.195 DEBUG (Thread-111 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - b'DASHy2fFAhHfRrI6vi7VXbUOQTeD' - MQTT Disconnected: 7
2024-05-25 16:05:36.255 DEBUG (Thread-110 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - b'DASHy2f4BaktzJvyNwSwRAcPRX6j' - MQTT connected: 0
2024-05-25 16:05:36.267 DEBUG (Thread-111 (_thread_main)) [yoto_api.YotoMQTTClient] yoto_api - b'DASHy2fFAhHfRrI6vi7VXbUOQTeD' - MQTT connected: 0
````

Unfortunately the media player is still not being updated. Is this a possible bug in the master branch?

Reverting back to 1.10.9 and things work again. I wonder if my previous issue was due to the fact that the device's battery fell below 10% and stopped pushing updates to MQTT? A complete guess, but if it happens again, I'll be sure to check the app too.

**Comment by cdnninja** [comment]
Could be.  Those logs look normal.  Connected 0 means we are connected to the mqtt service and waiting for them to push an update.   If you see a disconnect it's an issue.  It confirms the channel is open in a pretty fast loop just doesn't log that unless it detects disconnect.  I have found I have to sometimes send a poke to the mqtt server to get updates sent out.  Not sure why.

**Comment by WhimsySpoon** [comment]
Thanks for the detail.

Something is up in the master branch as neither of my devices work, but are working on 1.10.9.

**Comment by cdnninja** [comment]
Only differences between .9 and master are one added command to write data on battery updates and the media item.  Neither would impact messages coming into logs. 

I have seen strange Mqtt messaging though on when it will and won't.  Restarts sometimes triggering Mqtt to send updates.   Mine has been pretty stable lately though.

**Comment by WhimsySpoon** [comment]
OK, I'm back on master and it's working perfectly, including artwork. Most odd, but it looks great!

I'll keep an eye on it. If it stops updating again, I'll get logs and confirm app functionality.

**Comment by cdnninja** [comment]
It's more so using the app to trigger the update.  You will see the app send an update command when you view the playing card.  After that MQTT updates start flowing again.  If that solves it I can try mimicking that more often.  It does that already in startup but maybe the servers stop after some time.  

It seems inconsistent which makes this hard.

**Comment by cdnninja** [comment]
I just released an update that may help with this.  Since I didn't work on this integration much today I saw the issue too.   I re-arranged some code.  Now we wait to see what happens!

**Comment by WhimsySpoon** [comment]
Thanks so much. I had the issue a couple of times last night. Opening the app and firing a command fixed it immediately. Will try the latest now...

**Comment by cdnninja** [comment]
Lots has changed in the last week.  I dealt with a issue that after 24 hours mqtt updates would stop.  That seems to mostly have improved.

**Comment by cdnninja** [comment]
Things seem more stable.  Let me know if anything else wanting added.  I have covered almost all the items I personally wanted but happy to add more based on what people will use.

**Comment by bighead85** [comment]
Unsure if possible, but could the library be available in home assistant same as on Yoto app?
Thinking could be a great panel to select from for play on the desired device

**Comment by cdnninja** [comment]
Yes it can be.  I have been reading the home assistant dev docs trying to figure out the browse media feature.  It isn't well documented.

**Comment by bighead85** [comment]
I see what you mean, I see the Kodi and Plex add ons have it but cannot see what they doing special. 
They play pause is nice but be great to get next and previous buttons for media player device. I see yoto app gives these.

**Comment by WhimsySpoon** [comment]
Amazing work. So much has been achieved in such a short space of time.

I still find that updates stop flowing after an hour or two; I need to refresh the integration or press a button in the app. Does anyone else have this?

**Comment by cdnninja** [comment]
@WhimsySpoon  I am not seeing that.  Could you open a new issue for that and provide the debug logs?

**Comment by WhimsySpoon** [comment]
Of course. I'm away for a couple of weeks, but will do it when I return.

**Comment by bighead85** [comment]
> Amazing work. So much has been achieved in such a short space of time.
> 
> I still find that updates stop flowing after an hour or two; I need to refresh the integration or press a button in the app. Does anyone else have this?

I am seeing similar behavior, however reading the debug logs there are no errors or anything surprising.
My scan rate set to 15 minutes (which i think was the default)
Looks like Yoto correctly push out the media info for playing/changing media.
But the sensors are not updating as i would expect, only the media. Will open an issue with some example logging

**Comment by bighead85** [comment]
> I see what you mean, I see the Kodi and Plex add ons have it but cannot see what they doing special. They play pause is nice but be great to get next and previous buttons for media player device. I see yoto app gives these.

Did rather light investigation into adding next/previous track onto media player. Got the buttons to appear, however unclear how to actually use the api.yotoplay.com in order to see what the requests for MQTT would be to the actual api.

**Comment by cdnninja** [comment]
For next /previous track we would call yoto managers play_card and pass the current playing card number and either the previous or next chapter / track numbers. 

https://github.com/cdnninja/yoto_api/blob/e81ee26d16cfedc0b3f7a416c7086bba85f0be75/yoto_api/YotoManager.py#L70-L86

I haven't had time to confirm if I should increment track or chapter from current playing.  In theory it is just take those numbers, add or subtract and call the function via coordinator.  Coordinator method implemented here: 

https://github.com/cdnninja/yoto_ha/blob/1defa3b46f0aa0709800cb7ea0d741419ed90e0a/custom_components/yoto/coordinator.py#L141-L159

**Comment by cdnninja** [comment]
Added next/previous track as well as browse media.  Since I think the vast majority of key features are complete I am going to close this thread. As things come up of interest please create an issue and I can hopefully make it happen!
