### ISSUE TITLE
Unexpected error fetching yoto data

### ISSUE THREAD

**Issue by wilfriedroset** [cdnninja/yoto_ha#63]
Home assistant logs report the following error message

```
2024-05-25 14:41:20.706 ERROR (MainThread) [custom_components.yoto.coordinator] Unexpected error fetching yoto data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yoto/coordinator.py", line 62, in _async_update_data
    await self.hass.async_add_executor_job(self.yoto_manager.update_players_status)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 35, in update_players_status
    mqtt.update_status()
TypeError: YotoMQTTClient.update_status() missing 1 required positional argument: 'deviceId'
```

I'm using a yoto v2 `Firmware: v2.17.5-5` with home assistant running in a container `ghcr.io/home-assistant/raspberrypi4-homeassistant:stable` which contains `Core 2024.5.2` and `Frontend 20240501.1` with`yoto_ha 1.10.8`

context: I was looking for the reason why home assistant keeps showing my yoto as unavailable while the media player being on a connected to the wifi.

<img width="974" alt="Capture d’écran 2024-05-25 à 14 59 48" src="https://github.com/cdnninja/yoto_ha/assets/12611310/e3c9d3a5-f3a2-4766-8ca1-d97ee7e614aa">

**Comment by cdnninja** [comment]
This is fixed in latest update.

**Comment by wilfriedroset** [comment]
all good on my end
