### ISSUE TITLE
Devices become unavailable in master

### ISSUE THREAD

**Issue by WhimsySpoon** [cdnninja/yoto_ha#72]
I've been running the current `master` (upgraded from 1.12.2) version for the last hour or so. My device have since become unavailable with the following error:

````
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yoto/coordinator.py", line 64, in _async_update_data
    await self.hass.async_add_executor_job(self.yoto_manager.update_players_status)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yoto_api/YotoManager.py", line 36, in update_players_status
    self.mqtt_client.update_status(player.id)
                                   ^^^^^^^^^
AttributeError: 'str' object has no attribute 'id'
````

**Comment by cdnninja** [comment]
Latest master should fix this.  Thanks for the report!

**Comment by WhimsySpoon** [comment]
Installing latest master now. Will give it an hour and report back/close. Thanks!

**Comment by WhimsySpoon** [comment]
Has been fine since my last comment so closing the issue. Thanks again.
